ALTER TABLE `member`
    ADD COLUMN `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `member`
    ADD COLUMN `modified_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `order`
    CHANGE `updated_at` `modified_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `compensation`
    CHANGE `issued_at` `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `compensation`
    ADD COLUMN `modified_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `payment`
    CHANGE `created_at` `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `payment`
    ADD COLUMN `modified_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `store_owner`
    ADD COLUMN `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `store_owner`
    ADD COLUMN `modified_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `settlement`
    ADD COLUMN `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `settlement`
    ADD COLUMN `modified_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;